### ISSUE TITLE
How to train with my own dataset

### ISSUE THREAD

**Issue by bowfan94** [yuanwei1989/landmark-detection#1]

**Comment by percyfan** [comment]
Thanks for sharing the code, I have a question about it.

If I want to train with my own dataset (some 3d volumes made of 2D images), should I first make shape models of each volume from CreateShapeModel.m and then customize the train.py for training?

**Comment by sudharavali** [comment]
HI, 

How did you do landmark detection for your own dataset ? Please let me know
